### ISSUE TITLE
Tests are silently failing!

### ISSUE THREAD

**Issue by Vifon** [ranger/ranger#1457]
#### Runtime Environment
- Operating system and version: Gentoo Linux, x86_64
- Terminal emulator and version: N/A
- Python version: 3.6.5
- Ranger version/commit: cab56031
- Locale: en_US.utf8

#### Current Behavior

`make test` contains this part:

```
**********************************************************************
File "ranger/ext/human_readable.py", line 12, in __main__.human_readable
Failed example:
    human_readable(54)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.human_readable[0]>", line 1, in <module>
        human_readable(54)
      File "ranger/ext/human_readable.py", line 24, in human_readable
        if SettingsAware.settings.size_in_bytes:
    AttributeError: type object 'SettingsAware' has no attribute 'settings'
**********************************************************************
File "ranger/ext/human_readable.py", line 14, in __main__.human_readable
Failed example:
    human_readable(1500)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.human_readable[1]>", line 1, in <module>
        human_readable(1500)
      File "ranger/ext/human_readable.py", line 24, in human_readable
        if SettingsAware.settings.size_in_bytes:
    AttributeError: type object 'SettingsAware' has no attribute 'settings'
**********************************************************************
File "ranger/ext/human_readable.py", line 16, in __main__.human_readable
Failed example:
    human_readable(2 ** 20 * 1023)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.human_readable[2]>", line 1, in <module>
        human_readable(2 ** 20 * 1023)
      File "ranger/ext/human_readable.py", line 24, in human_readable
        if SettingsAware.settings.size_in_bytes:
    AttributeError: type object 'SettingsAware' has no attribute 'settings'
**********************************************************************
1 items had failures:
   3 of   3 in __main__.human_readable
***Test Failed*** 3 failures.
```

**and** we don't get notified about it when running `make test` and it's affecting Travis CI.

#### Expected Behavior

If a test (doctest in this case) is failing, `make test` should at the very least exit with a non-zero exit code.

#### Context

This problem in particular is caused by [SettingsAware.setting](https://github.com/ranger/ranger/blob/6549b810ae108325fd1bf2634e10884c55413bc8/ranger/ext/human_readable.py#L24) being [assigned](https://github.com/ranger/ranger/blob/a807090fd7d3b21b26d05baf962b6d6a0d615f92/ranger/core/main.py#L90) only during the ranger startup procedure and it doesn't exist when we're running this test.

The bug was seemingly introduced in 6549b810ae108325fd1bf2634e10884c55413bc8 but it's just the tip of the iceberg: such tests would silently fail either way.

#### Possible Solutions

As this is basically a 3-in-1 issue, we need to:

- [ ] fix the `size_in_bytes` support in `human_readable.py` during the testing either by making it no longer needed or making the settings available there
- [x] **make our test fail properly**
- [ ] possibly make the settings accessible during the testing (should fix number 1 actually)

#### Steps to reproduce

Run `make test` on a current `master` branch or check the Travis CI output.

**Comment by Vifon** [comment]
Initially I wanted to initialize `SettingsAware` before running the tests but it proved troublesome as the `Settings` object also depends on the ranger initialization in the current state.
