### ISSUE TITLE
Fails to apply file name filter upon startup

### ISSUE THREAD

**Issue by cherio** [ranger/ranger#2133]
command `filter` doesn't work when used upon startup:
`ranger --cmd='filter cron' /etc`
An error message gets displayed at the bottom saying "`'NoneType' object has no attribute 'files'`".
The same error message shows when using `scout` command

This functionality _works as expected_ in Ubuntu 20.04 but fails to apply the filter in Debian 9 and Ubuntu 18.04.

#### Runtime Environment

- Operating system and version: Debian 9, Ubuntu 18.04
- Terminal emulator and version: any
- ranger & Python version:
$> ranger --version # Debian 9
ranger-stable 1.7.1

Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516]

also

$> ranger --version # Ubuntu 18.04
ranger-stable 1.8.1

Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0]

- Locale: en_US.UTF-8

#### Current Behavior
Shows the error and the unfiltered directory content

#### Expected Behavior
Should show files matching the filter

#### Context
I am trying to display a directory content with a pre-configured file filter

#### Possible Solutions
This would be a guess only. Errors and misbehavior occur in the systems running ranger with python 2. It works well in Ubuntu 20.04 which runs under python 3. My guess this must be a compatibility issue.

#### Steps to reproduce
Run command
`ranger --cmd='filter cron' /etc`

Observe the error at the bottom; the result file list is NOT filtered

**Comment by toonn** [comment]
I suspect 20.04 just has a newer version of ranger.

**Comment by cherio** [comment]
> I suspect 20.04 just has a newer version of ranger.

No need to suspect that. It's a fact:

```
$ ranger --version
ranger version: ranger 1.9.3
Python version: 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
Locale: en_US.UTF-8
```
The question is if there is a way to get the fix into the previous LTS distributions.

**Comment by toonn** [comment]
I'm sure debian package maintainers would accept a patch if you do the hard work identifying it. I'd recommend using git bisect to figure out what exact commit fixed this.

**Comment by cherio** [comment]
I am having a strong feeling that Ubuntu/Debian maintainers may not have enough incentive to patch the distros any time soon. It will likely not happen at all. The only solution then is to install from source (this fixed ranger in my Ubuntu 16.04 & 18.04):
```
/bin/bash <<"EOF"
[ $(whoami) = "root" ] || { echo "run as root"; exit; }
apt-get -y remove ranger
apt-get -y install build-essential python3-setuptools
cd; mkdir -p ~/tmp; cd tmp
git clone https://github.com/ranger/ranger
cd ./ranger/
make install
rm -rf ~/tmp
EOF
```

**Comment by toonn** [comment]
Afaik debian and ubuntu maintainers are fairly responsive. As long as you submit a patch they can simply include with the distribution and clearly explain why they should include the patch I'm sure they'd accept it. They won't be figuring out the patch for you though.
