### ISSUE TITLE
'OpenStruct' object has no attribute 'update_preview'

### ISSUE THREAD

**Issue by rdpate** [ranger/ranger#12]
test/tc_loader.py was broken by commit a30885773f28e93b8bbe716a4ba444e90e3ba4d8 (and hasn't been fixed since):

```
$ git checkout a30885773f28e93b8bbe716a4ba444e90e3ba4d8
HEAD is now at a308857... fsobject.fsobject: Update previews when file changes
$ make test
................................E
======================================================================
ERROR: test_loader (tc_loader.Test1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kniht/code/ranger/test/tc_loader.py", line 51, in test_loader
    dir.load_content(schedule=True)
  File "test/../ranger/fsobject/directory.py", line 266, in load_content
    self.load()
  File "test/../ranger/fsobject/fsobject.py", line 184, in load
    self.fm.update_preview(self.path)
AttributeError: 'OpenStruct' object has no attribute 'update_preview'

----------------------------------------------------------------------
Ran 63 tests in 0.133s

FAILED (errors=1)
make: *** [test] Error 1
```

I'm not familiar enough with the code to be sure, but it appears the correct fix is simply to mock self.fm.update_preview to do nothing:

```
--- a/test/tc_loader.py
+++ b/test/tc_loader.py
@@ -35,7 +35,7 @@ TESTDIR = realpath(join(dirname(__file__), 'testdir'))
 class Test1(unittest.TestCase):
        def test_loader(self):
                loader = Loader()
-               fm = OpenStruct(loader=loader)
+               fm = OpenStruct(loader=loader, update_preview=lambda path: None)
                SettingsAware.settings = Fake()
                FileManagerAware.fm = fm
```
